#logging:
# level:
#    org:
#      springframework: INFO
#    root: ERROR
#  pattern:
#    console: '%-5level %logger{36} - %msg%n'
spring:
  datasource:
    password: 
    url: jdbc:mysql://localhost:3306/biblio?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
